---
title: An R Markdown document converted from "D:/Vidhi/Forecasting/project/Walmart_DL.ipynb"
output: html_document
---

```{python}
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"{device}" " is available.")
```

```{python}
# from google.colab import files
# data_to_load = files.upload()


from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/My Drive/essec assignment/Forecasting/'
```

```{python}
  dateparse = lambda x: datetime.strptime(x, '%Y-%m-%d')
  #all data reading here  
  df = pd.read_csv(file_path+"Projectdata.csv", date_parser=dateparse)
  df['Datetime'] = pd.to_datetime(df.date, format='%Y-%m-%d')
  df.columns

  column_index_to_pick = 2
  print(df.columns[column_index_to_pick])
  df = df[["Datetime",df.columns[column_index_to_pick]]]
```

```{python}
import plotly.graph_objs as go
from plotly.offline import iplot

def plot_dataset(df, title):
    data = []
    
    value = go.Scatter(
        x=df.index,
        y=df.value,
        mode="lines",
        name="values",
        marker=dict(),
        text=df.index,
        line=dict(color="rgba(0,0,0, 0.3)"),
    )
    data.append(value)

    layout = dict(
        title=title,
        xaxis=dict(title="Date", ticklen=5, zeroline=False),
        yaxis=dict(title="Value", ticklen=5, zeroline=False),
    )

    fig = dict(data=data, layout=layout)
    iplot(fig)
    
```

```{python}
df = df.set_index(['Datetime'])
df = df.rename(columns={df.columns[0]: 'value'})

df.index = pd.to_datetime(df.index)
if not df.index.is_monotonic:
    df = df.sort_index()
    
plot_dataset(df, title='Walmart sales data')
    
```

RNNs are a type of neural network architecture which is mainly used to detect patterns in sequential data.LSTMs, a special type of RNNs, were designed to handle such long range dependencies much better than standard RNNs.
Feature engineering for LSTM:
Inorder to give each time series a memory, we create lag parameters for each Y(t), which are the memory of the time series for lag p, this lag is usually identified from -
1. We extract Month, day, day of the week and week of the year variables from the 
datetime of the timeseries and use them as an added feature for our model.
2. We also tried to generate cyclical features for the above generated date parameters and evaluated it for our model.
3. Inorder to add extra features like holidays and snap days, we create two more variables for the same.
4. We use OneHotEncoder to encode all the data before passing to the parameters.
5. It is considered a good practice to scale the data as it is prepared for any Neural Network, we  use MinMaxScaler for this.
6. Our LSTM is a plain Linear model with a single hidden layer and batch size of 32. We train it for 100 epochs and have a dropout of 0.2.
7. In the above vanilla model, we saw that the RMSSE was as close to the Linear Regression model, thus showing much scope of improvement upon added hidden layers to the neural network and modification of other parameters

```{python}
def generate_time_lags(df, n_lags):
    df_n = df.copy()
    for n in range(1, n_lags + 1):
        df_n[f"lag{n}"] = df_n["value"].shift(n)
    df_n = df_n.iloc[n_lags:]
    return df_n

input_dim = 30

df_timelags = generate_time_lags(df, input_dim)
df_timelags
```

```{python}
# df_features = (
#                 df
#                 .assign(hour = df.index.hour)
#                 .assign(day = df.index.day)
#                 .assign(month = df.index.month)
#                 .assign(day_of_week = df.index.dayofweek)
#                 .assign(week_of_year = df.index.week)
#               )

# df_features.columns

df_features = (
                df_timelags
                .assign(hour = df_timelags.index.hour)
                .assign(day = df_timelags.index.day)
                .assign(month = df_timelags.index.month)
                .assign(day_of_week = df_timelags.index.dayofweek)
                .assign(week_of_year = df_timelags.index.week)
              )

df_features.columns
```

```{python}
def onehot_encode_pd(df, cols):
    for col in cols:
        dummies = pd.get_dummies(df[col], prefix=col)
    
    return pd.concat([df, dummies], axis=1).drop(columns=cols)

# df_features2 = onehot_encode_pd(df_features, ['month','day','day_of_week','week_of_year'])
df_features2 = onehot_encode_pd(df_features, ['month'])
df_features2 = onehot_encode_pd(df_features2, ['day'])
df_features2 = onehot_encode_pd(df_features2, ['day_of_week'])
df_features2 = onehot_encode_pd(df_features2, ['week_of_year'])
df_features2.columns
```

```{python}
#NOTTT DOING this right now

def generate_cyclical_features(df, col_name, period, start_num=0):
    kwargs = {
        f'sin_{col_name}' : lambda x: np.sin(2*np.pi*(df[col_name]-start_num)/period),
        f'cos_{col_name}' : lambda x: np.cos(2*np.pi*(df[col_name]-start_num)/period)    
             }
    return df.assign(**kwargs).drop(columns=[col_name])

# df_features = generate_cyclical_features(df_features, 'hour', 24, 0)
# df_features = generate_cyclical_features(df_features, 'day_of_week', 7, 0)
# df_features = generate_cyclical_features(df_features, 'month', 12, 1)
# df_features = generate_cyclical_features(df_features, 'week_of_year', 52, 0)

df_features2.columns

```

```{python}
#create holidays from calendar data
calendar_data = pd.read_csv(file_path+"calendar.csv", date_parser=dateparse)
calendar_data['date'] = pd.to_datetime(calendar_data.date, format='%Y-%m-%d')
calendar_data.dtypes
calendar_data["holidays"] = np.where( (calendar_data["event_name_1"].notnull()) | (calendar_data["event_name_2"].notnull()), 1, 0)
calendar_data.head()
```

```{python}
from datetime import date
import holidays

# us_holidays = holidays.US()

def is_holiday(date):
    date = date.replace(hour = 0)
    return 1 if (date in calendar_data['date']) else 0

def add_holiday_col(df, holidays):
    return df.assign(is_holiday = df.index.to_series().apply(is_holiday))


df_features2 = add_holiday_col(df_features2, calendar_data[["date","holidays"]])
df_features2.columns
df_features2
```

```{python}
df_features2.columns
```

```{python}
from sklearn.model_selection import train_test_split

def feature_label_split(df, target_col):
    y = df[[target_col]]
    X = df.drop(columns=[target_col])
    return X, y

def train_val_test_split(df, target_col, test_ratio):
    val_ratio = test_ratio / (1 - test_ratio)
    X, y = feature_label_split(df, target_col)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_ratio, shuffle=False)
    X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=val_ratio, shuffle=False)
    return X_train, X_val, X_test, y_train, y_val, y_test

X_train, X_val, X_test, y_train, y_val, y_test = train_val_test_split(df_features2, 'value', 0.2)
```

```{python}
from sklearn.preprocessing import MinMaxScaler, StandardScaler, MaxAbsScaler, RobustScaler

def get_scaler(scaler):
    scalers = {
        "minmax": MinMaxScaler,
        "standard": StandardScaler,
        "maxabs": MaxAbsScaler,
        "robust": RobustScaler,
    }
    return scalers.get(scaler.lower())()
```

```{python}

scaler = get_scaler('minmax')
X_train_arr = scaler.fit_transform(X_train)
X_val_arr = scaler.transform(X_val)
X_test_arr = scaler.transform(X_test)

y_train_arr = scaler.fit_transform(y_train)
y_val_arr = scaler.transform(y_val)
y_test_arr = scaler.transform(y_test)
```

```{python}
X_train.columns
```

```{python}
from torch.utils.data import TensorDataset, DataLoader

# batch_size = 64
batch_size = 32

train_features = torch.Tensor(X_train_arr)
train_targets = torch.Tensor(y_train_arr)
val_features = torch.Tensor(X_val_arr)
val_targets = torch.Tensor(y_val_arr)
test_features = torch.Tensor(X_test_arr)
test_targets = torch.Tensor(y_test_arr)

train = TensorDataset(train_features, train_targets)
val = TensorDataset(val_features, val_targets)
test = TensorDataset(test_features, test_targets)

train_loader = DataLoader(train, batch_size=batch_size, shuffle=False, drop_last=True)
val_loader = DataLoader(val, batch_size=batch_size, shuffle=False, drop_last=True)
test_loader = DataLoader(test, batch_size=batch_size, shuffle=False, drop_last=True)
test_loader_one = DataLoader(test, batch_size=1, shuffle=False, drop_last=True)
```

class LSTMModel(nn.Module):

```{python}
import torch.nn.functional as F
#@title
class LSTMModel(nn.Module):
    """LSTMModel class extends nn.Module class and works as a constructor for LSTMs.

       LSTMModel class initiates a LSTM module based on PyTorch's nn.Module class.
       It has only two methods, namely init() and forward(). While the init()
       method initiates the model with the given input parameters, the forward()
       method defines how the forward propagation needs to be calculated.
       Since PyTorch automatically defines back propagation, there is no need
       to define back propagation method.

       Attributes:
           hidden_dim (int): The number of nodes in each layer
           layer_dim (str): The number of layers in the network
           lstm (nn.LSTM): The LSTM model constructed with the input parameters.
           fc (nn.Linear): The fully connected layer to convert the final state
                           of LSTMs to our desired output shape.

    """
    def __init__(self, input_dim, hidden_dim, layer_dim, output_dim):
        """The __init__ method that initiates a LSTM instance.

        Args:
            input_dim (int): The number of nodes in the input layer
            hidden_dim (int): The number of nodes in each layer
            layer_dim (int): The number of layers in the network
            output_dim (int): The number of nodes in the output layer
            dropout_prob (float): The probability of nodes being dropped out

        """
        super(LSTMModel, self).__init__()

        # Defining the number of layers and the nodes in each layer
        self.hidden_dim = hidden_dim
        self.layer_dim = layer_dim

        # LSTM layers
        self.lstm = nn.LSTM(
            input_dim, hidden_dim, layer_dim, batch_first=True, dropout=0.2
        )

        # Fully connected layer
        self.fc = nn.Linear(hidden_dim, 30)
        self.relu = nn.ReLU(inplace=True)
        # self.fc1 = nn.Linear(50, 30)
        # self.fc2 = nn.Linear(30, 15)
        self.fc3 = nn.Linear(30, output_dim)

    def forward(self, x):
        """The forward method takes input tensor x and does forward propagation

        Args:
            x (torch.Tensor): The input tensor of the shape (batch size, sequence length, input_dim)

        Returns:
            torch.Tensor: The output tensor of the shape (batch size, output_dim)

        """
        # Initializing hidden state for first input with zeros
        h0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).requires_grad_()

        # Initializing cell state for first input with zeros
        c0 = torch.zeros(self.layer_dim, x.size(0), self.hidden_dim).requires_grad_()

        # We need to detach as we are doing truncated backpropagation through time (BPTT)
        # If we don't, we'll backprop all the way to the start even after going through another batch
        # Forward propagation by passing in the input, hidden state, and cell state into the model
        out, (hn, cn) = self.lstm(x, (h0.detach(), c0.detach()))

        # Reshaping the outputs in the shape of (batch_size, seq_length, hidden_size)
        # so that it can fit into the fully connected layer
        out = out[:, -1, :]

        # Convert the final state to our desired output shape (batch_size, output_dim)
        out = self.relu(self.fc(out))
        # out = self.relu(self.fc1(out))
        # out = self.relu(self.fc2(out))
        out = self.fc3(out)

        return out
```

```{python}
def get_model(model, model_params):
    models = {
        "lstm": LSTMModel
    }
    return models.get(model.lower())(**model_params)
```

class Optimization:
x_batch = x_batch.view([batch_size, -1, n_features]).to(device)

```{python}
#@title
class Optimization:
    """Optimization is a helper class that allows training, validation, prediction.

    Optimization is a helper class that takes model, loss function, optimizer function
    learning scheduler (optional), early stopping (optional) as inputs. In return, it
    provides a framework to train and validate the models, and to predict future values
    based on the models.

    Attributes:
        model (RNNModel, LSTMModel, GRUModel): Model class created for the type of RNN
        loss_fn (torch.nn.modules.Loss): Loss function to calculate the losses
        optimizer (torch.optim.Optimizer): Optimizer function to optimize the loss function
        train_losses (list[float]): The loss values from the training
        val_losses (list[float]): The loss values from the validation
        last_epoch (int): The number of epochs that the models is trained
    """
    def __init__(self, model, loss_fn, optimizer):
        """
        Args:
            model (RNNModel, LSTMModel, GRUModel): Model class created for the type of RNN
            loss_fn (torch.nn.modules.Loss): Loss function to calculate the losses
            optimizer (torch.optim.Optimizer): Optimizer function to optimize the loss function
        """
        self.model = model
        self.loss_fn = loss_fn
        self.optimizer = optimizer
        self.train_losses = []
        self.val_losses = []
        
    def train_step(self, x, y):
        """The method train_step completes one step of training.

        Given the features (x) and the target values (y) tensors, the method completes
        one step of the training. First, it activates the train mode to enable back prop.
        After generating predicted values (yhat) by doing forward propagation, it calculates
        the losses by using the loss function. Then, it computes the gradients by doing
        back propagation and updates the weights by calling step() function.

        Args:
            x (torch.Tensor): Tensor for features to train one step
            y (torch.Tensor): Tensor for target values to calculate losses

        """
        # Sets model to train mode
        self.model.train()

        # Makes predictions
        yhat = self.model(x)

        # Computes loss
        loss = torch.sqrt(self.loss_fn(y, yhat))
        # RMSE_loss.backward()    
        # loss = self.loss_fn(y, yhat)

        # Computes gradients
        loss.backward()

        # Updates parameters and zeroes gradients
        self.optimizer.step()
        self.optimizer.zero_grad()

        # Returns the loss
        return loss.item()

    def train(self, train_loader, val_loader, batch_size=64, n_epochs=50, n_features=1):
        """The method train performs the model training

        The method takes DataLoaders for training and validation datasets, batch size for
        mini-batch training, number of epochs to train, and number of features as inputs.
        Then, it carries out the training by iteratively calling the method train_step for
        n_epochs times. If early stopping is enabled, then it  checks the stopping condition
        to decide whether the training needs to halt before n_epochs steps. Finally, it saves
        the model in a designated file path.

        Args:
            train_loader (torch.utils.data.DataLoader): DataLoader that stores training data
            val_loader (torch.utils.data.DataLoader): DataLoader that stores validation data
            batch_size (int): Batch size for mini-batch training
            n_epochs (int): Number of epochs, i.e., train steps, to train
            n_features (int): Number of feature columns

        """
        model_path = f'{self.model}_{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}'

        for epoch in range(1, n_epochs + 1):
            batch_losses = []
            for x_batch, y_batch in train_loader:
                x_batch = x_batch.view([batch_size, -1, n_features]).to(device)
                y_batch = y_batch.to(device)
                loss = self.train_step(x_batch, y_batch)
                batch_losses.append(loss)
            training_loss = np.mean(batch_losses)
            self.train_losses.append(training_loss)

            with torch.no_grad():
                batch_val_losses = []
                for x_val, y_val in val_loader:
                    x_val = x_val.view([batch_size, -1, n_features]).to(device)
                    y_val = y_val.to(device)
                    self.model.eval()
                    yhat = self.model(x_val)
                    val_loss = self.loss_fn(y_val, yhat).item()
                    batch_val_losses.append(val_loss)
                validation_loss = np.mean(batch_val_losses)
                self.val_losses.append(validation_loss)

            if (epoch <= 10) | (epoch % 50 == 0):
                print(
                    f"[{epoch}/{n_epochs}] Training loss: {training_loss:.4f}\t Validation loss: {validation_loss:.4f}"
                )

        torch.save(self.model.state_dict(), model_path)

    def evaluate(self, test_loader, batch_size=1, n_features=1):
        """The method evaluate performs the model evaluation

        The method takes DataLoaders for the test dataset, batch size for mini-batch testing,
        and number of features as inputs. Similar to the model validation, it iteratively
        predicts the target values and calculates losses. Then, it returns two lists that
        hold the predictions and the actual values.

        Note:
            This method assumes that the prediction from the previous step is available at
            the time of the prediction, and only does one-step prediction into the future.

        Args:
            test_loader (torch.utils.data.DataLoader): DataLoader that stores test data
            batch_size (int): Batch size for mini-batch training
            n_features (int): Number of feature columns

        Returns:
            list[float]: The values predicted by the model
            list[float]: The actual values in the test set.

        """
        with torch.no_grad():
            predictions = []
            values = []
            for x_test, y_test in test_loader:
                x_test = x_test.view([batch_size, -1, n_features]).to(device)
                y_test = y_test.to(device)
                self.model.eval()
                yhat = self.model(x_test)
                predictions.append(yhat.to(device).detach().numpy())
                values.append(y_test.to(device).detach().numpy())

        return predictions, values

    def plot_losses(self):
        """The method plots the calculated loss values for training and validation
        """
        plt.plot(self.train_losses, label="Training loss")
        plt.plot(self.val_losses, label="Validation loss")
        plt.legend()
        plt.title("Losses")
        plt.show()
        plt.close()
```

```{python}
#TESTING if this model works

import torch.optim as optim

input_dim = len(X_train.columns)
output_dim = 1
hidden_dim = 64
layer_dim = 3
batch_size = 32
dropout = 0.2
n_epochs = 100
learning_rate = 1e-3
weight_decay = 1e-6

model_params = {'input_dim': input_dim,
                'hidden_dim' : hidden_dim,
                'layer_dim' : layer_dim,
                'output_dim' : output_dim}

# model = get_model('lstm', model_params)
model = LSTMModel(**model_params)

loss_fn = nn.MSELoss(reduction="mean")
optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)


opt = Optimization(model=model, loss_fn=loss_fn, optimizer=optimizer)
opt.train(train_loader, val_loader, batch_size=batch_size, n_epochs=n_epochs, n_features=input_dim)
opt.plot_losses()

predictions, values = opt.evaluate(
    test_loader_one,
    batch_size=1,
    n_features=input_dim
)
```

```{python}
def inverse_transform(scaler, df, columns):
    for col in columns:
        df[col] = scaler.inverse_transform(df[col])
    return df


def format_predictions(predictions, values, df_test, scaler):
    vals = np.concatenate(values, axis=0).ravel()
    preds = np.concatenate(predictions, axis=0).ravel()
    df_result = pd.DataFrame(data={"value": vals, "prediction": preds}, index=df_test.head(len(vals)).index)
    df_result = df_result.sort_index()
    df_result = inverse_transform(scaler, df_result, [["value", "prediction"]])
    return df_result


df_result = format_predictions(predictions, values, X_test, scaler)
df_result
```

```{python}
!pip install sktime
```

```{python}
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sktime.performance_metrics.forecasting import mean_squared_scaled_error

def calculate_metrics(df):
    result_metrics = {'mae' : mean_absolute_error(df.value, df.prediction),
                      'rmse' : mean_squared_error(df.value, df.prediction) ** 0.5,
                      'r2' : r2_score(df.value, df.prediction),
                      'rmsse': mean_squared_scaled_error(df.value, df.prediction, y_train=y_train, 
                                                         multioutput= 'uniform_average', square_root=True)
                     }
    
    print("Mean Absolute Error:       ", result_metrics["mae"])
    print("Root Mean Squared Error:   ", result_metrics["rmse"])
    print("R^2 Score:                 ", result_metrics["r2"])
    print("RMSSE Score:                 ", result_metrics["rmsse"])
    return result_metrics

result_metrics = calculate_metrics(df_result)
```

```{python}
from sklearn.linear_model import LinearRegression

def build_baseline_model(df, test_ratio, target_col):
    X, y = feature_label_split(df, target_col)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_ratio, shuffle=False
    )
    model = LinearRegression()
    model.fit(X_train, y_train)
    prediction = model.predict(X_test)

    result = pd.DataFrame(y_test)
    result["prediction"] = prediction
    result = result.sort_index()

    return result

df_baseline = build_baseline_model(df_features, 0.2, 'value')
baseline_metrics = calculate_metrics(df_baseline)
```



```{python}
rmsse = {}
```

```{python}
for column_index_to_pick in range(2,19):
  dateparse = lambda x: datetime.strptime(x, '%Y-%m-%d')
  #all data reading here  
  df = pd.read_csv(file_path+"Projectdata.csv", date_parser=dateparse)
  df['Datetime'] = pd.to_datetime(df.date, format='%Y-%m-%d')
  # df.columns

  # column_index_to_pick = 1
  column_name = df.columns[column_index_to_pick]
  df = df[["Datetime",df.columns[column_index_to_pick]]]

  df = df.set_index(['Datetime'])
  df = df.rename(columns={df.columns[0]: 'value'})

  df.index = pd.to_datetime(df.index)
  if not df.index.is_monotonic:
      df = df.sort_index()

  input_dim = 7
  df_timelags = generate_time_lags(df, input_dim)

  df_features = (
                  df_timelags
                  .assign(hour = df_timelags.index.hour)
                  .assign(day = df_timelags.index.day)
                  .assign(month = df_timelags.index.month)
                  .assign(day_of_week = df_timelags.index.dayofweek)
                  .assign(week_of_year = df_timelags.index.week)
                )
  # df_features.columns

  df_features2 = onehot_encode_pd(df_features, ['month'])
  df_features2 = onehot_encode_pd(df_features2, ['day'])
  df_features2 = onehot_encode_pd(df_features2, ['day_of_week'])
  df_features2 = onehot_encode_pd(df_features2, ['week_of_year'])
  # df_features2.columns

  calendar_data = pd.read_csv(file_path+"calendar.csv", date_parser=dateparse)
  calendar_data['date'] = pd.to_datetime(calendar_data.date, format='%Y-%m-%d')
  # calendar_data.dtypes
  calendar_data["holidays"] = np.where( (calendar_data["event_name_1"].notnull()) | (calendar_data["event_name_2"].notnull()), 1, 0)
  # calendar_data.head()

  df_features2 = add_holiday_col(df_features2, calendar_data[["date","holidays"]])
  # df_features2.columns
  # df_features2

  X_train, X_val, X_test, y_train, y_val, y_test = train_val_test_split(df_features2, 'value', 0.2)

  scaler = get_scaler('minmax')
  X_train_arr = scaler.fit_transform(X_train)
  X_val_arr = scaler.transform(X_val)
  X_test_arr = scaler.transform(X_test)

  y_train_arr = scaler.fit_transform(y_train)
  y_val_arr = scaler.transform(y_val)
  y_test_arr = scaler.transform(y_test)

  from torch.utils.data import TensorDataset, DataLoader

  # batch_size = 64
  batch_size = 32

  train_features = torch.Tensor(X_train_arr)
  train_targets = torch.Tensor(y_train_arr)
  val_features = torch.Tensor(X_val_arr)
  val_targets = torch.Tensor(y_val_arr)
  test_features = torch.Tensor(X_test_arr)
  test_targets = torch.Tensor(y_test_arr)

  train = TensorDataset(train_features, train_targets)
  val = TensorDataset(val_features, val_targets)
  test = TensorDataset(test_features, test_targets)

  train_loader = DataLoader(train, batch_size=batch_size, shuffle=False, drop_last=True)
  val_loader = DataLoader(val, batch_size=batch_size, shuffle=False, drop_last=True)
  test_loader = DataLoader(test, batch_size=batch_size, shuffle=False, drop_last=True)
  test_loader_one = DataLoader(test, batch_size=1, shuffle=False, drop_last=True)

  input_dim = len(X_train.columns)
  output_dim = 1
  hidden_dim = 64
  layer_dim = 3
  batch_size = 32
  dropout = 0.2
  n_epochs = 150
  learning_rate = 1e-3
  weight_decay = 1e-6

  model_params = {'input_dim': input_dim,
                  'hidden_dim' : hidden_dim,
                  'layer_dim' : layer_dim,
                  'output_dim' : output_dim}

  model = get_model('lstm', model_params)

  loss_fn = nn.MSELoss()
  optimizer = optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)


  opt = Optimization(model=model, loss_fn=loss_fn, optimizer=optimizer)
  opt.train(train_loader, val_loader, batch_size=batch_size, n_epochs=n_epochs, n_features=input_dim)
  opt.plot_losses()

  predictions, values = opt.evaluate(
      test_loader_one,
      batch_size=1,
      n_features=input_dim
  )


  df_result = format_predictions(predictions, values, X_test, scaler)
  result_metrics = calculate_metrics(df_result)
  rmsse[column_name] = result_metrics["rmsse"]
```

```{python}
print(rmsse)

# {'Hobbies_CA_1': 0.7656939042398, 'Household_1_CA_1': 0.7965365350851297, 'Household_2_CA_1': 0.8503918058375421, 
#  'Foods_1_CA_1': 1.0953491320935562, 'Foods_2_CA_1': 0.6793413772516582, 'Foods_3_CA_1': 0.47509861906261946, 
#  'Hobbies_CA_2': 0.9132461281046284, 'Household_1_CA_2': 0.8739190454853121, 'Household_2_CA_2': 0.8277853341897083, 
#  'Foods_1_CA_2': 6.483449980559171, 'Foods_2_CA_2': 1.1805376830269405, 'Foods_3_CA_2': 1.0278460371569509, 
#  'Hobbies_CA_3': 1.182396762207118, 'Household_1_CA_3': 1.0230286365663384, 'Household_2_CA_3': 0.8626254183301303,
#  'Foods_1_CA_3': 1.0433096445921504, 'Foods_2_CA_3': 0.7406501135825783, 'Foods_3_CA_3': 0.7388000556176572}
```

